import sys
import os

headerfilename = sys.argv[1]+'.h'
cppfilename    = sys.argv[1]+'.cpp'

headerfile_basename = os.path.basename(headerfilename)

headerlines = []
headerlines.append("// file generated by copy_files_to_c_header.py \n");
headerlines.append("// each file's contents are copied into static char strings \n\n");
headerlines.append("#if !defined("+headerfile_basename.replace(".","_").upper()+"_INCLUDED) \n");
headerlines.append("#define "+headerfile_basename.replace(".","_").upper()+"_INCLUDED \n");

srclines = []
srclines.append("// file generated by copy_files_to_c_header.py \n");
srclines.append("// each file's contents are copied into static char strings \n\n");
srclines.append("#include <"+headerfile_basename+'>\n')  

for filename in sys.argv[2:len(sys.argv)]:
  infile = open(filename,"r")
  inlines = infile.readlines()
  
  headerlines.append("extern const char * ")
  headerlines.append(os.path.basename(filename).replace(".","_"))
  headerlines.append(";\n")  
  
  srclines.append("const char * ")
  srclines.append(os.path.basename(filename).replace(".","_"))
  srclines.append(" = ")
  
  for line in inlines:
    if line[len(line)-1] == '\n':
      line = line[:len(line)-1]      
    line = "\"" + line[0:len(line)] + "\\n\"" + "\\\n"      
    srclines.append(line)
    
  srclines.append(";\n\n")
  
headerlines.append("#endif\n");

headerfile = open(headerfilename,"w")
headerfile.writelines(headerlines);
headerfile.close();

srcfile = open(cppfilename,"w")
srcfile.writelines(srclines);
srcfile.close();

